### ISSUE TITLE
mock dependency

### ISSUE THREAD

**Issue by pgajdos** [Itxaka/yarb#17]
Please remove superfluous dependency on mock

**Comment by pgajdos** [comment]
Perhaps something like this:
https://build.opensuse.org/package/view_file/home:pgajdos:python/python-yarb/python-yarb-use-unittest-mock.patch
or we can use unittest.mock unconditionally.

**Comment by Itxaka** [comment]
Hi @pgajdos, this is mainly abandoned since 2008, we should probably drop it from Factory.


If you really need this I can modify it and push a new version, but it would be better to drop it altogether :)

**Comment by pgajdos** [comment]
Thanks @Itxaka for your insight, I have filled delete request from Factory. Thanks!
